### ISSUE TITLE
add dark mode CSS class to edit mode

### ISSUE THREAD

**Issue by yourhead** [yourhead/s4#48]
the class should be public, obvious, and specified to behave so that 3rd party stacks can rely on it and use it to style their own edit-mode UI.

**Comment by yourhead** [comment]
in stacks v4.0.0 beta 1

here's an example of the class. this will place a red border around the UI div of a stack only in dark mode:

```css
.dark div.mez {
    border: 2px solid red;
}
```
